/** Milestone 6: stack management on Elasticsearch and OpenSearch. */
import { expect, test, type ElectronApplication, type Page } from '@playwright/test'
import { CLUSTERS, connect, launch } from './helpers'

test.describe.configure({ mode: 'serial' })

let app: ElectronApplication
let page: Page

test.beforeAll(async () => {
  ;({ app, page } = await launch())
})
test.afterAll(async () => app?.close())

const nav = (label: string) => page.locator('.stack-item', { hasText: label }).click()
const editor = () => page.locator('.sec-editor')

test('ES: users list with reserved built-ins, create a role and a user', async () => {
  await connect(page, CLUSTERS.es9)
  await page.getByRole('button', { name: 'Stack management' }).click()
  await expect(page.locator('.sec-head')).toContainText('native realm')
  await expect(page.locator('.sec-row.users', { hasText: 'elastic' }).first()).toContainText('reserved')

  await nav('Roles')
  await page.getByRole('button', { name: 'Create role' }).click()
  await editor().getByLabel('Role name').fill('e2e_listings_reader')
  await editor().getByLabel('Cluster privileges').fill('monitor')
  await editor().getByLabel('Cluster privileges').press('Enter')
  await editor().getByLabel('Indices').fill('listings*')
  await editor().getByLabel('Indices').press('Enter')
  await editor().getByRole('button', { name: 'Save role' }).click()
  await expect(page.locator('.toast')).toContainText('Saved role e2e_listings_reader')
  await expect(page.locator('.sec-row.roles', { hasText: 'e2e_listings_reader' })).toContainText('listings*')

  await nav('Users')
  await page.getByRole('button', { name: 'Create user' }).click()
  await editor().getByLabel('Username').fill('e2e_user')
  await editor().getByLabel('Password').fill('E2e-Pass_123')
  await editor().getByLabel('Full name').fill('E2E User')
  await editor().getByLabel('Roles').fill('e2e_listings_reader')
  await editor().getByLabel('Roles').press('Enter')
  await editor().getByRole('button', { name: 'Create user' }).click()
  const row = page.locator('.sec-row.users', { hasText: 'e2e_user' })
  await expect(row).toContainText('e2e_listings_reader')
  await expect(row).toContainText('Enabled')
  await page.screenshot({ path: 'e2e/screens/40-security.png' })

  await row.click()
  await editor().getByRole('button', { name: 'Disable' }).click()
  await expect(row).toContainText('Disabled')
  page.once('dialog', (d) => d.accept())
  await row.click()
  await editor().getByRole('button', { name: 'Delete' }).click()
  await expect(row).toHaveCount(0)
  await nav('Roles')
  page.once('dialog', (d) => d.accept())
  await page.locator('.sec-row.roles', { hasText: 'e2e_listings_reader' }).click()
  await editor().getByRole('button', { name: 'Delete' }).click()
  await expect(page.locator('.sec-row.roles', { hasText: 'e2e_listings_reader' })).toHaveCount(0)
})

test('ES: API keys are shown once and can be invalidated', async () => {
  await nav('API keys')
  await page.getByRole('button', { name: 'Create API key' }).click()
  await page.getByLabel('Name').fill('e2e-key')
  await page.getByRole('dialog').getByRole('button', { name: 'Create' }).click()
  await expect(page.getByLabel('Encoded API key')).not.toBeEmpty()
  await page.getByRole('button', { name: 'Done' }).click()
  const row = page.locator('.sec-row.keys', { hasText: 'e2e-key' }).first()
  await expect(row).toContainText('elastic')
  page.once('dialog', (d) => d.accept())
  await row.getByRole('button', { name: 'Invalidate' }).click()
  await expect(page.locator('.sec-row.keys', { hasText: 'e2e-key' })).toHaveCount(0)
})

test('ES: data and cluster pages', async () => {
  await nav('Nodes')
  await expect(page.locator('.sec-row.nodes.static')).toHaveCount(1)
  await nav('Ingest pipelines')
  await expect(page.locator('.sec-head')).toContainText('Ingest pipelines')
  await nav('Index lifecycle')
  await expect(page.locator('.sec-head')).toContainText('ILM policies')
  await nav('Settings')
  await expect(page.locator('.card-head', { hasText: 'persistent' })).toBeVisible()
  await nav('Tasks')
  await page.getByRole('button', { name: 'Include internal tasks' }).click()
  await expect(page.locator('.sec-row.tasks.static', { hasText: 'cluster:monitor/tasks/lists' }).first()).toBeVisible()
})

test('OpenSearch: security plugin users, FLS role and tenants', async () => {
  await connect(page, CLUSTERS.os2)
  await page.getByRole('button', { name: 'Stack management' }).click()
  await expect(page.locator('.sec-head')).toContainText('internal users')
  await expect(page.locator('.stack-item', { hasText: 'API keys' })).toHaveCount(0)
  await nav('Roles')
  await page.getByRole('button', { name: 'Create role' }).click()
  await expect(editor().locator('.os-note')).toContainText('Security plugin')
  await editor().getByLabel('Role name').fill('e2e_os_reader')
  await editor().getByLabel('Indices').fill('listings*')
  await editor().getByLabel('Indices').press('Enter')
  await editor().getByLabel('Excluded fields').fill('price')
  await editor().getByLabel('Excluded fields').press('Enter')
  await editor().getByLabel('Document-level query').fill('{"term":{"status":"active"}}')
  await editor().getByRole('button', { name: 'Save role' }).click()
  const row = page.locator('.sec-row.roles', { hasText: 'e2e_os_reader' })
  await expect(row).toContainText('FLS')
  await expect(row).toContainText('DLS')
  page.once('dialog', (d) => d.accept())
  await row.click()
  await editor().getByRole('button', { name: 'Delete' }).click()
  await expect(row).toHaveCount(0)

  await nav('Tenants')
  await page.getByLabel('Tenant name').fill('e2e_tenant')
  await page.getByLabel('Tenant description').fill('from e2e')
  await page.getByRole('button', { name: 'Add tenant' }).click()
  const t = page.locator('.sec-row.tenants', { hasText: 'e2e_tenant' })
  await expect(t).toContainText('from e2e')
  page.once('dialog', (d) => d.accept())
  await t.getByRole('button', { name: 'Delete' }).click()
  await expect(t).toHaveCount(0)
  await nav('Index lifecycle')
  await expect(page.locator('.sec-head')).toContainText('ISM policies')
})
